#!/bin/bash

# SellerFi Pre-Test QA Checklist Generator
# Validates API routes, database migrations, and indexing

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                    SELLERFIN PRE-TEST QA CHECKLIST                         ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check Prisma schema validity
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. DATABASE VALIDATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  [ ] Prisma Schema Validation"
npx prisma validate > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo -e "      ${GREEN}✓${NC} Schema is valid"
else
    echo -e "      ${RED}✗${NC} Schema validation failed"
fi

echo ""
echo "  [ ] Database Migrations Status"
MIGRATION_STATUS=$(npx prisma migrate status 2>&1 | grep -i "up to date" || echo "")
if [ ! -z "$MIGRATION_STATUS" ]; then
    echo -e "      ${GREEN}✓${NC} All migrations applied"
else
    echo -e "      ${YELLOW}⚠${NC} Check migration status manually"
fi

echo ""
echo "  [ ] Database Indexes"
echo "      Expected indexes:"
echo "      • User: email (unique), role, createdAt"
echo "      • Listing: sellerId, assetType, status, city+state, createdAt, isFeatured"
echo "      • Dealroom: listingId, buyerId, sellerId, status, lastActivityAt"
echo "      • Message: dealroomId, senderId, createdAt"
echo "      • Document: dealroomId, listingId, docType, signatureStatus"
echo "      • BuyerProfile: canAccessNDA, qualificationBadge"
echo "      • BuyerIntentScore: totalScore, level"
echo "      • Activity: userId, dealroomId, activityType, createdAt"
echo "      • Embedding: sourceType, sourceId (with unique constraint)"
echo "      • PaymentHistory: userId, status, createdAt, stripePaymentIntentId (unique)"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2. API ROUTES REGRESSION CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  AUTHENTICATION & AUTHORIZATION"
echo "  ──────────────────────────────────────────────────────────────────────────"
echo "  [ ] POST /api/auth/[...nextauth] - NextAuth handler"
echo "      • Signup flow (email/password)"
echo "      • Login flow (email/password)"
echo "      • Session management"
echo "      • JWT token generation"
echo "      • Default role assignment (BUYER)"
echo ""

echo "  BUYER PROFILE"
echo "  ──────────────────────────────────────────────────────────────────────────"
echo "  [ ] GET  /api/buyer/profile"
echo "      • Returns buyer profile with completeness score"
echo "      • Includes canAccessNDA flag"
echo "      • Requires authentication"
echo ""

echo "  LISTINGS"
echo "  ──────────────────────────────────────────────────────────────────────────"
echo "  [ ] Server Actions: lib/actions/listings.ts"
echo "      • createListing() - Seller-only, validates required fields"
echo "      • getListings() - Public browse, filters by status=ACTIVE"
echo "      • getListing() - Public detail view, includes financials"
echo "      • Filters: assetType, price range, location, minSellerFiancing%"
echo ""

echo "  TERM SHEET & FINANCIAL CALCULATIONS"
echo "  ──────────────────────────────────────────────────────────────────────────"
echo "  [ ] Server Actions: lib/actions/term-sheet.ts"
echo "      • updateFinancingTerms() - Seller-only, validates structure"
echo "      • getListingForEdit() - Seller-only, includes all financials"
echo "  [ ] POST /api/ai/suggest-terms"
echo "      • Rule-based term suggestions"
echo "      • Requires authentication"
echo "      • Validates input (askingPrice, assetType, financials)"
echo "  [ ] POST /api/ai/estimate-payment"
echo "      • Calculates monthly payment estimates"
echo "      • Handles seller carry + bank financing"
echo "      • Returns confidence level"
echo ""

echo "  DEALROOM & MESSAGING"
echo "  ──────────────────────────────────────────────────────────────────────────"
echo "  [ ] Server Actions: lib/actions/dealroom.ts"
echo "      • createDealroom() - Creates on NDA acceptance"
echo "      • acceptNDA() - Sets ndaAccepted = true, creates dealroom"
echo "      • sendMessage() - Validates dealroom membership"
echo "      • getDealroom() - Includes messages, activities, intent score"
echo "      • getMyDealrooms() - User-specific dealrooms"
echo "      • markMessagesAsRead() - Updates read receipts"
echo "  [ ] GET  /api/dealrooms/[id]/messages/stream"
echo "      • Server-Sent Events for real-time messaging"
echo "      • Handles message and read receipt events"
echo "      • Requires dealroom membership"
echo "  [ ] GET  /api/dealrooms/[id]/listing-info"
echo "      • Returns listing premium status for dealroom"
echo "      • Requires dealroom membership"
echo "  [ ] POST /api/dealrooms/[id]/qa"
echo "      • RAG-based Q&A using pgvector"
echo "      • Requires NDA acceptance"
echo "      • Validates dealroom membership"
echo ""

echo "  DOCUMENTS & UPLOADS"
echo "  ──────────────────────────────────────────────────────────────────────────"
echo "  [ ] POST /api/documents/upload"
echo "      • File upload handling (multipart/form-data)"
echo "      • Validates file type and size"
echo "      • Creates Document record"
echo "      • Stores locally in /uploads"
echo "  [ ] GET  /api/uploads/[...path]"
echo "      • Serves uploaded files"
echo "      • Validates access (dealroom membership + NDA)"
echo "  [ ] Server Actions: lib/actions/documents.ts"
echo "      • getDocuments() - Returns dealroom/listing documents"
echo "      • Validates access permissions"
echo ""

echo "  BILLING & MONETIZATION"
echo "  ──────────────────────────────────────────────────────────────────────────"
echo "  [ ] POST /api/billing/upgrade"
echo "      • Creates Stripe Checkout Session"
echo "      • Validates seller ownership"
echo "      • Checks listing status (must be ACTIVE)"
echo "      • Idempotency check (already premium)"
echo "  [ ] POST /api/billing/webhook"
echo "      • Stripe webhook handler"
echo "      • Validates webhook signature"
echo "      • Fulfills premium upgrade (sets isPremium = true)"
echo "      • Creates PaymentHistory record"
echo "      • Idempotency via stripeCheckoutSessionId"
echo ""

echo "  AI CO-PILOT"
echo "  ──────────────────────────────────────────────────────────────────────────"
echo "  [ ] POST /api/ai/suggest-terms"
echo "      • Rule-based logic (SDE/EBITDA + industry defaults)"
echo "      • Returns: downPayment, sellerCarry, rates, years"
echo "      • Includes confidence score and reasoning"
echo "  [ ] POST /api/ai/estimate-payment"
echo "      • Calculates blended monthly payment"
echo "      • Handles seller carry + optional bank financing"
echo "      • Returns confidence level"
echo ""

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3. DATABASE INDEX VALIDATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  Critical Indexes (Performance):"
echo "  [ ] User.email (unique) - Login lookups"
echo "  [ ] Listing.status + assetType - Browse filtering"
echo "  [ ] Listing.city + state - Location filtering"
echo "  [ ] Dealroom.listingId + buyerId (unique) - Prevent duplicates"
echo "  [ ] Message.dealroomId + createdAt - Message history"
echo "  [ ] BuyerProfile.canAccessNDA - NDA gating"
echo "  [ ] Document.dealroomId + docType - Document access"
echo "  [ ] Embedding.sourceType + sourceId - Vector search"
echo "  [ ] Activity.dealroomId + activityType - Activity timeline"
echo "  [ ] PaymentHistory.userId + status - Payment tracking"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "4. ENVIRONMENT VARIABLES VALIDATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  [ ] DATABASE_URL - PostgreSQL connection string"
echo "  [ ] AUTH_SECRET - NextAuth secret"
echo "  [ ] AUTH_URL / NEXTAUTH_URL - Base URL for auth callbacks"
echo "  [ ] STRIPE_SECRET_KEY - Stripe API key (for billing)"
echo "  [ ] STRIPE_PUBLISHABLE_KEY - Stripe public key"
echo "  [ ] STRIPE_WEBHOOK_SECRET - Webhook signature validation"
echo "  [ ] OPENAI_API_KEY (optional) - For future LLM features"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "5. SECURITY & ACCESS CONTROL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  [ ] Authentication Required:"
echo "      • All API routes (except public listings browse)"
echo "      • Server actions validate user session"
echo ""
echo "  [ ] Authorization Checks:"
echo "      • Seller-only: createListing, updateFinancingTerms, upgrade listing"
echo "      • Buyer-only: createBuyerProfile, sign NDA"
echo "      • Dealroom membership: sendMessage, view documents, Q&A"
echo "      • Listing ownership: edit terms, upgrade listing"
echo ""
echo "  [ ] NDA Gating:"
echo "      • Detailed financials hidden until NDA signed"
echo "      • Document access requires NDA"
echo "      • Q&A requires NDA"
echo "      • BuyerProfile.canAccessNDA based on capital requirements"
echo ""
echo "  [ ] Input Validation:"
echo "      • Zod schemas for all form inputs"
echo "      • File upload size/type restrictions"
echo "      • SQL injection prevention (Prisma parameterized queries)"
echo "      • XSS prevention (React auto-escaping)"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "6. DATA INTEGRITY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  [ ] Foreign Key Constraints:"
echo "      • BuyerProfile.userId → User.id"
echo "      • Listing.sellerId → User.id"
echo "      • Dealroom.listingId → Listing.id"
echo "      • Dealroom.buyerId → User.id"
echo "      • Dealroom.sellerId → User.id"
echo "      • Message.dealroomId → Dealroom.id"
echo "      • Document.dealroomId → Dealroom.id"
echo ""
echo "  [ ] Unique Constraints:"
echo "      • User.email (unique)"
echo "      • BuyerProfile.userId (one profile per user)"
echo "      • Dealroom.listingId + buyerId (one dealroom per listing+buyer)"
echo "      • PaymentHistory.stripePaymentIntentId (idempotency)"
echo ""
echo "  [ ] Required Fields:"
echo "      • User: email, passwordHash, role"
echo "      • Listing: title, sellerId, assetType, status"
echo "      • Dealroom: listingId, buyerId, sellerId, status"
echo "      • Message: content, senderId, dealroomId"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "7. FUNCTIONAL VALIDATION CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  AUTHENTICATION FLOW"
echo "  ──────────────────────────────────────────────────────────────────────────"
echo "  [ ] User signup creates account with BUYER role"
echo "  [ ] Login creates session and JWT token"
echo "  [ ] Protected routes redirect to /auth/login if not authenticated"
echo "  [ ] Session persists across page refreshes"
echo ""

echo "  LISTING CREATION & MANAGEMENT"
echo "  ──────────────────────────────────────────────────────────────────────────"
echo "  [ ] Seller can create listing with all required fields"
echo "  [ ] Listing defaults to DRAFT status"
echo "  [ ] Seller can edit financing terms"
echo "  [ ] Term sheet builder calculates payment preview"
echo "  [ ] Financial snapshots (multiples, DSCR) display correctly"
echo "  [ ] Premium upgrade flow works end-to-end"
echo ""

echo "  BUYER PROFILE & NDA GATING"
echo "  ──────────────────────────────────────────────────────────────────────────"
echo "  [ ] Buyer profile completeness score calculates correctly"
echo "  [ ] canAccessNDA flag updates based on capital requirements"
echo "  [ ] NDA button shows/hides based on canAccessNDA"
echo "  [ ] NDA acceptance creates dealroom"
echo "  [ ] Detailed financials visible after NDA signed"
echo ""

echo "  DEALROOM & MESSAGING"
echo "  ──────────────────────────────────────────────────────────────────────────"
echo "  [ ] Messages send and receive in real-time (SSE)"
echo "  [ ] Read receipts update when messages viewed"
echo "  [ ] Activity timeline logs all dealroom actions"
echo "  [ ] Buyer intent score updates on NDA + messages"
echo "  [ ] Documents panel shows all dealroom documents"
echo ""

echo "  DOCUMENTS & RAG"
echo "  ──────────────────────────────────────────────────────────────────────────"
echo "  [ ] Document upload creates Document record"
echo "  [ ] Embeddings generated for text documents"
echo "  [ ] Q&A returns relevant document chunks"
echo "  [ ] Vector search uses pgvector cosine similarity"
echo ""

echo "  BILLING & MONETIZATION"
echo "  ──────────────────────────────────────────────────────────────────────────"
echo "  [ ] Upgrade button creates Stripe Checkout Session"
echo "  [ ] Webhook fulfills premium upgrade"
echo "  [ ] Premium badge displays on listing cards"
echo "  [ ] PaymentHistory record created"
echo ""

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "8. PERFORMANCE & SCALABILITY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  [ ] Database queries use indexes (no full table scans)"
echo "  [ ] Pagination implemented for listings browse"
echo "  [ ] Server-Sent Events for real-time updates (not polling)"
echo "  [ ] File uploads stored efficiently (local for now, cloud-ready)"
echo "  [ ] Vector embeddings chunked appropriately (max 1000 tokens)"
echo "  [ ] RAG queries limit results (top 5 chunks)"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "9. ERROR HANDLING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  [ ] API routes return appropriate HTTP status codes"
echo "  [ ] Error messages are user-friendly (not exposing internals)"
echo "  [ ] Database errors are caught and logged"
echo "  [ ] Stripe webhook errors are handled gracefully"
echo "  [ ] File upload errors are validated before processing"
echo "  [ ] Authentication errors redirect to login"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "10. UI/UX VALIDATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "  [ ] Responsive design (mobile, tablet, desktop)"
echo "  [ ] Loading states for async operations"
echo "  [ ] Error messages display clearly"
echo "  [ ] Success toasts for user actions"
echo "  [ ] Form validation shows inline errors"
echo "  [ ] Premium badges display correctly"
echo "  [ ] Buyer profile dashboard updates dynamically"
echo "  [ ] Dealroom UI layout (messages left, info right)"
echo "  [ ] Auto-scroll to latest message"
echo "  [ ] User avatars display correctly"

echo ""
echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                         READY FOR ACCEPTANCE TESTING                       ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Next Steps:"
echo "  1. Review and check off completed items above"
echo "  2. Run manual acceptance tests per docs/SELLERFIN_ACCEPTANCE_TESTS.md"
echo "  3. Log results in docs/SELLERFIN_TEST_LOG.md"
echo ""

