/**
 * Icon Button Accessibility Audit
 * 
 * Finds icon-only buttons missing aria-label for screen readers.
 * 
 * Usage:
 *   npx tsx scripts/accessibility/icon-button-audit.ts
 */

import { execSync } from "child_process"
import * as fs from "fs"

interface Issue {
  file: string
  line: number
  code: string
  issue: string
}

const issues: Issue[] = []

function findIconButtonsWithoutLabels() {
  try {
    // Find Button components with size="icon" but no aria-label
    const result = execSync(
      `rg -n 'size="icon"' app components -g "*.tsx" -g "*.ts" -A 2 -B 2`,
      { encoding: "utf-8", maxBuffer: 10 * 1024 * 1024 }
    )

    const lines = result.split("\n")
    let currentFile = ""
    let currentLine = 0
    let contextLines: string[] = []

    lines.forEach((line) => {
      const fileMatch = line.match(/^([^:]+):(\d+):/)
      if (fileMatch) {
        currentFile = fileMatch[1]
        currentLine = parseInt(fileMatch[2])
      }

      contextLines.push(line)

      if (line.includes('size="icon"')) {
        const context = contextLines.slice(-5).join("\n")

        // Check if aria-label exists in context
        if (!context.includes("aria-label")) {
          issues.push({
            file: currentFile,
            line: currentLine,
            code: line.substring(line.indexOf(":") + 1).trim(),
            issue: "Icon button missing aria-label",
          })
        }

        contextLines = []
      }
    })
  } catch (error) {
    // No matches
  }
}

async function main() {
  console.log("🔍 Starting Icon Button Accessibility Audit...\n")

  findIconButtonsWithoutLabels()

  console.log("═══════════════════════════════════════════════════════════")
  console.log("        ICON BUTTON ACCESSIBILITY AUDIT RESULTS")
  console.log("═══════════════════════════════════════════════════════════\n")

  console.log(`Total Issues Found: ${issues.length}\n`)

  if (issues.length === 0) {
    console.log("🎉 All icon buttons have proper accessibility labels!\n")
    return
  }

  console.log("Issues Found:\n")
  console.log("─────────────────────────────────────────────────────────\n")

  issues.slice(0, 50).forEach((issue, index) => {
    console.log(`${index + 1}. ${issue.file}:${issue.line}`)
    console.log(`   ${issue.issue}`)
    console.log(`   Code: ${issue.code.substring(0, 80)}...`)
    console.log()
  })

  if (issues.length > 50) {
    console.log(`   ... and ${issues.length - 50} more\n`)
  }

  // Generate report
  const report = `# Icon Button Accessibility Audit Report

**Date:** ${new Date().toISOString().split("T")[0]}  
**Total Issues:** ${issues.length}

## Issues

${issues
  .map(
    (issue, index) => `
### ${index + 1}. ${issue.file}:${issue.line}

**Issue:** ${issue.issue}

\`\`\`tsx
${issue.code}
\`\`\`

**Fix:** Add \`aria-label\` prop:
\`\`\`tsx
<Button size="icon" aria-label="Descriptive action">
  <Icon />
</Button>
\`\`\`
`
  )
  .join("\n")}

---

## Best Practices

All icon-only buttons MUST have an \`aria-label\` attribute:

\`\`\`tsx
// ✅ Good
<Button size="icon" aria-label="Delete item">
  <Trash2 className="h-4 w-4" />
</Button>

// ❌ Bad
<Button size="icon">
  <Trash2 className="h-4 w-4" />
</Button>
\`\`\`

---

*Generated by Icon Button Accessibility Audit Script*
`

  fs.writeFileSync("ICON_BUTTON_AUDIT_REPORT.md", report)

  console.log("📄 Full report saved to: ICON_BUTTON_AUDIT_REPORT.md")
  console.log("\n💡 Fix: Add aria-label to all icon-only buttons")

  if (issues.length > 0) {
    process.exit(1)
  }
}

main().catch((error) => {
  console.error("❌ Error:", error)
  process.exit(1)
})
